config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :users do
    member do
      get 'profile'
      get 'matches'
    end
  end
  resources :posts, only: [:index, :new, :create, :destroy]
  resources :comments
  resource :interest, only: [:create, :destroy]

  get   'auth/facebook/callback', to: 'sessions#create'
  match '/sign_out', to: 'sessions#destroy', via: :delete

  post   'create_friendship' => 'friendships#create'
  delete 'delete_friendship' => 'friendships#destroy'
  post   'reject_friendship' => 'friendships#reject'

  get 'matches/get_email' => 'users#get_email'

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.create(comment_param)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.js
    end
  end

  private

  def comment_param
    params.require(:comment).permit(:text, :post_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div data-comment-id="<%= comment.id %>">
  <strong> <%= comment.user.name %> </strong>
  <% if comment.user == current_user %>
    <%= link_to 'x', comment_path(comment.id), method: :delete, remote: true %>
  <% end %>
  <p><%= comment.text %> </p>
</div>

app/views/comments/_form.html.erb
<div>
  <%= form_for :comment, url: comments_path, remote: true do |form| %>
    <%= form.hidden_field :post_id, value: post.id %>
    <div>
      <%= form.text_field :text, placeholder: 'Comment text is here' %>
    </div>
    <div>
      <%= form.submit 'Add comment' %>
    </div>
  <% end %>
</div>

app/views/comments/create.js.erb
$post = $("div").find("[data-post-id=<%=@comment.post.id%>]");
$comments = $post.find("div.comments");
$post.find('input#comment_text').val('');
$post.find('input#comment_post_id').val("<%=@comment.post.id%>");
$comments.append("<div data-comment-id=<%=@comment.id %>><strong> <%= @comment.user.name %> </strong> <% if @comment.user.id == current_user.id %> <%= escape_javascript(link_to 'x', comment_path(@comment.id), method: :delete, remote: true)%> <% end %> <p><%= @comment.text %> </p></div>");

app/views/comments/destroy.js.erb
$post = $("div").find("[data-post-id=<%= @comment.post.id %>]");
$post.find("[data-comment-id=<%= @comment.id %>]").remove();