config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :users do
    member do
      get 'profile'
      get 'matches'
    end
  end
  resources :posts, only: [:index, :new, :create, :destroy]
  resources :comments
  resource :interest, only: [:create, :destroy]

  get   'auth/facebook/callback', to: 'sessions#create'
  match '/sign_out', to: 'sessions#destroy', via: :delete

  post   'create_friendship' => 'friendships#create'
  delete 'delete_friendship' => 'friendships#destroy'
  post   'reject_friendship' => 'friendships#reject'

  get 'matches/get_email' => 'users#get_email'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :friendships, dependent: :destroy
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id', dependent: :destroy
  has_many :user_interests
  has_many :interests, through: :user_interests
  has_many :posts
  has_many :comments

  has_attached_file :avatar,
                    storage: :s3,
                    s3_host_name: ENV['S3_HOST_NAME'],
                    style: { medium: '370x370', thumb: '100x100' }

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  default_scope { order('id DESC') }

  def self.sign_in_from_facebook(auth)
    find_by(provider: auth['provider'], uid: auth['uid']) || create_user_from_facebook(auth)
  end

  def self.create_user_from_facebook(auth)
    create(
      avatar: process_uri(auth['info']['image'] + '?width=9999'),
      email: auth['info']['email'],
      provider: auth['provider'],
      uid: auth['uid'],
      name: auth['info']['name'],
      gender: auth['extra']['raw_info']['gender'],
      date_of_birth: auth['extra']['raw_info']['birthday'],
      location: auth['info']['location'],
      bio: auth['extra']['raw_info']['bio']
    )
  end

  # Friendship Methods
  def request_match(user2)
    friendships.create(friend: user2)
  end

  def accept_match(user2)
    friendships.where(friend: user2).first.update_attribute(:state, 'ACTIVE')
  end

  def remove_match(user2)
    inverse_friendship = inverse_friendships.where(user_id: user2).first

    if inverse_friendship
      inverse_friendships.where(user_id: user2).first.destroy
    else
      friendships.where(friend_id: user2).first.destroy
    end
  end

  # Friendship Methods

  # Filter Methods
  def self.gender(user)
    case user.interest
    when 'Male'
      where('gender = ?', 'male')
    when 'Female'
      where('gender = ?', 'female')
    else
      all
    end
  end

  def self.available_to_connect(current_user)
    @r = current_user.friendships.map(&:friend)
    @r2 = current_user.inverse_friendships.map(&:user)
    @rejected = current_user.inverse_friendships.where(state: 'reject').map(&:user)
    @active = current_user.inverse_friendships.where(state: 'ACTIVE').map(&:user)
    u = User.where.not(id: current_user.id) - @r - @rejected - @active
  end

  def self.not_me(user)
    where.not(id: user.id)
  end

  def matches(current_user)
    friendships.where(state: 'pending').map(&:friend) + current_user.friendships.where(state: 'ACTIVE').map(&:friend) + current_user.inverse_friendships.where(state: 'ACTIVE').map(&:user)
  end
  #
  def rejected(current_user)
    friendships.where(state: 'reject').map(&:friend) + current_user.friendships.where(state: 'reject').map(&:friend) + current_user.inverse_friendships.where(state: 'reject').map(&:user)
  end
  # Filter Methods

  private

  def self.process_uri(uri)
    avatar_url = URI.parse(uri)
    avatar_url.scheme = 'https'
    avatar_url.to_s
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login
  before_action :set_user, only: %i[edit profile update destroy get_email matches]

  def index
    @users = User.available_to_connect(current_user)
    if current_user.interest != 'Both'
      @users.select! { |o| o.gender == current_user.interest }
    end
    @users.uniq

    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    authorize! :update, @user
  end

  def update
    if @user.update(users_params)
      respond_to do |format|
        format.html { redirect_to users_path }
      end
    else
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
    if @user.destroy
      session[:user_id] = nil
      session[:omniauth] = nil
      redirect_to root_path
    else
      redirect_to edit_user_path(@user)
    end
  end

  def profile; end

  def matches
    authorize! :read, @user
    @matches = current_user.friendships.where(state: 'ACTIVE').map(&:friend) + current_user.inverse_friendships.where(state: 'ACTIVE').map(&:user)
    @users = User.available_to_connect(current_user)
    if current_user.interest != 'Both'
      @users.select! { |o| o.gender == current_user.interest }
    end
    @users.uniq
  end

  def get_email
    respond_to do |format|
      format.js
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def users_params
    params.require(:user).permit(:interest, :bio, :avatar, :location, :date_of_birth, :gender)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def name(user)
    if user.name
      case user
      when user
        user.name.partition(' ').first
      when @user
        user.name.partition(' ').first
      end
    end
  end

  def age(user)
    if user.date_of_birth
      case user
      when user
        age = Date.today.year - user.date_of_birth.year
        age
      when @user
        age = Date.today.year - @user.date_of_birth.year
        age
      end
    end
  end

  def location(user)
    if user.location
      case user
      when user
        user.location.partition(',').first
      when @user
        @user.location.partition(',').first
      end
    end
  end
end

app/views/users/_match.html.erb
<tr>
	<th scope="row"><%= image_tag "#{match.avatar}", size: "30x30" %></th>
	<td><%= link_to match.name, profile_user_path(match.id) %></td>
	<td><%= match.updated_at.strftime('%m/%d/%Y') %></td>
	<td class="text-right">

	<%= link_to matches_get_email_path(id: "#{match.id}"), :data => {toggle: "tooltip", placement: "top" }, title: "Get Email", remote: :true  do %>
		<i class="fa fa fa-envelope"></i>
	<% end %>

	<%= link_to delete_friendship_path(friend_id: match.id), :data => {toggle: "tooltip", placement: "top", confirm: "Are you sure you want to unmatch with #{match.name} ?" }, title: "Unmatch", id: "delete_friendship", method: :delete do %>
		<i class="fa fa fa-times"></i>
	<% end %>
	</td>
</tr>

app/views/users/_user.html.erb
<li id="<%= user.id %>">
    <div class="img"><%= image_tag user.avatar.url, height: '370', width: '370' %></div>
    <div class="user-name pull-left">
      <%= link_to profile_user_path(user.id) do %><b><%= name(user) %></b>, <%= age(user) %><% end %>
    </div>
    <div class="user-location text-right"><i class="fa fa-map-marker"></i> <%= location(user) %></div>
    <div class="like"></div>
    <div class="dislike"></div>
    <%= link_to "", create_friendship_path(friend_id: user.id), id: "user_#{user.id}", method: :post, :remote => true %>
</li>

app/views/users/edit.html.erb
<%= simple_form_for(@user, url: url_for(:action => 'update', :controller => 'users'), html: {multipart: true} ) do |f| %>

<div class="container">
	<div class="dropdown">
		<%= f.input :interest, collection: ['Male', 'Female', 'Both'], :input_html => { class: 'form-control'} %>
	</div>
	<%= f.input :gender, collection: ['Male', 'Female'], :input_html => { class: 'form-control'} %>
	<%# f.input :interest, as: :hidden, label: false %>

	<h4 class="text-uppercase"><small>Profile Description</small></h4>
	<%= f.input :bio, as: :text, class: "form-control", label: false, :input_html => { :rows => 5, class: 'form-control' } %>

	<h4 class="text-uppercase"><small>City</small></h4>
	<%= f.input :location, label: false, :input_html => { class: 'form-control' } %>

	<h4 class="text-uppercase"><small>Age</small></h4>
	<%= f.input :date_of_birth, as: :string, label: false, :input_html => { class: 'form-control' } %>

	<br />

        <div class="text-center">
          <div class="fileinput fileinput-new" data-provides="fileinput">
              <div class="fileinput-new thumbnail" style="width: 100px; height: 75px;">
                <img data-src="holder.js/100%x100%" src="<%= @user.avatar %>">
              </div>
              <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 100px; max-height: 75px;"></div>
              <div>
                <span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span><%= f.file_field :avatar %></span>
                <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
              </div>
            </div>
        </div>

        <%= f.button :submit, class: "btn btn-primary btn-block btn-xs", value: "Submit" %>
        <br />
        <%= link_to 'Cancel your account', user_path(current_user.id), method: :delete, data: { confirm: "Are you sure?"}, title: "Delete Account" %>
</div>

<% end %>
<div class="container">
  <div class="dropdown">
    <%= form_for :interest, url: interest_path, remote: true do |form| %>
      <%= form.select :interest, interests: (Interest.all - current_user.interests).map { |m| [m.name, m.id] } %>
      <%= form.submit %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
	$('.gender').click(function(){
		$("#dropdownMenu1").text( $(this).text() );
		$("#dropdownMenu1").append('<span class="caret"></span>');
		$("#user_interest").val( $(this).text() );
	});
</script>

app/views/users/get_email.js.erb
swal("Email", "<%= @user.email %>");

app/views/users/index.html.erb
<div class="container">
	<br>
<% if @users.count > 0 %>
<div id="users-container">
	<div class="row">
		<div class="text-center">
			<div class="wrap">

				<div id="tinderslide">
					<ul>
						<%= render @users %>
					</ul>
				</div>


				<div class="actions">
					<a href="#" class="dislike"><i class="fa fa-times"></i></a>
					<a href="#" class="like"><i class="fa fa-heart"></i></a>
				</div>


			</div>
		</div>
	</div>
</div>
</div>


<div class="spinner center_spinner">
	<div class="rect1"></div>
	<div class="rect2"></div>
	<div class="rect3"></div>
	<div class="rect4"></div>
	<div class="rect5"></div>
</div>

<script type="text/javascript">
$("#tinderslide > ul li").tsort({attr: "id"});
</script>
<% else %>
	<h1 class="text-center">No more users at this time</h1>
<% end %>

app/views/users/index.js.erb
<% if @users.count > 0 %>
 // $("#tinderslide ul").replaceWith('<%= escape_javascript(render(partial: @users, collection: @users)) %>');
 // $("#tinderslide > ul > li").tsort({attr: "id"});
 // $("#tinderslide").jTinder();
<% else %>
    $('#users-container').replaceWith('<h1 class="text-center">No more users at this time</h1>');
<% end %>

app/views/users/matches.html.erb
<div class="container">

	<table class="table table-striped">
		<thead>
			<tr>
				<th></th>
				<th>Name</th>
				<th>Matched on</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<%= render partial: "match", collection: @matches %>
		</tbody>
	</table>


</div>


<script type="text/javascript">
	$(function () {
		$('[data-toggle="tooltip"]').tooltip();
	});
  <% if @users.count <= 0 %>
      $('#users-container').replaceWith('<h1 class="text-center">No more users at this time</h1>');
  <% end %>
</script>

app/views/users/profile.html.erb
<div class="container">
  <div class="wrap">
    <div class="profile-box">
      <div class="img">
        <%= image_tag @user.avatar, width: "100%", height: "100%" %>
      </div>
      <div class="user-name pull-left"><a href=""><b><%= name(@user) %></b>, <%= age(@user) %></a></div>
      <div class="user-location text-right"><i class="fa fa-map-marker"></i> <%= location(@user) %></div>
      <div class="description">
        <h4 class="text-uppercase"><small>Description</small></h4>
        <p class="small"><%= @user.bio %></p>
      </div>
    </div>
  </div>
</div>
</div>