config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :users do
    member do
      get 'profile'
      get 'matches'
    end
  end
  resources :posts, only: [:index, :new, :create, :destroy]
  resources :comments
  resource :interest, only: [:create, :destroy]

  get   'auth/facebook/callback', to: 'sessions#create'
  match '/sign_out', to: 'sessions#destroy', via: :delete

  post   'create_friendship' => 'friendships#create'
  delete 'delete_friendship' => 'friendships#destroy'
  post   'reject_friendship' => 'friendships#reject'

  get 'matches/get_email' => 'users#get_email'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :update, User do |u|
      u == user
    end

    can :read, User do |u|
      u == user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/interest.rb
class Interest < ApplicationRecord
  has_many :user_interests
  has_many :users, through: :user_interests

  validates :name, presence: true,
                   uniqueness: true
end

app/models/post.rb
class Post < ApplicationRecord
  attr_accessor :attachment_file_name
  belongs_to :interest
  belongs_to :user
  has_many :comments

  validates :text, presence: true

  has_attached_file :attachment,
                    storage: :s3,
                    s3_host_name: ENV['S3_HOST_NAME'],
                    style: { medium: '370x370', thumb: '100x100' }

    validates_attachment_content_type :attachment,
    :content_type => ['video/mp4'],
    :if => :is_type_of_video?
  validates_attachment_content_type :attachment,
     :content_type => ['image/png', 'image/jpeg', 'image/jpg', 'image/gif'],
     :if => :is_type_of_image?
  has_attached_file :attachment

  protected
  def is_type_of_video?
    attachment.content_type =~ %r(video)
  end

  def is_type_of_image?
    attachment.content_type =~ %r(image)
  end
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :friendships, dependent: :destroy
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id', dependent: :destroy
  has_many :user_interests
  has_many :interests, through: :user_interests
  has_many :posts
  has_many :comments

  has_attached_file :avatar,
                    storage: :s3,
                    s3_host_name: ENV['S3_HOST_NAME'],
                    style: { medium: '370x370', thumb: '100x100' }

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  default_scope { order('id DESC') }

  def self.sign_in_from_facebook(auth)
    find_by(provider: auth['provider'], uid: auth['uid']) || create_user_from_facebook(auth)
  end

  def self.create_user_from_facebook(auth)
    create(
      avatar: process_uri(auth['info']['image'] + '?width=9999'),
      email: auth['info']['email'],
      provider: auth['provider'],
      uid: auth['uid'],
      name: auth['info']['name'],
      gender: auth['extra']['raw_info']['gender'],
      date_of_birth: auth['extra']['raw_info']['birthday'],
      location: auth['info']['location'],
      bio: auth['extra']['raw_info']['bio']
    )
  end

  # Friendship Methods
  def request_match(user2)
    friendships.create(friend: user2)
  end

  def accept_match(user2)
    friendships.where(friend: user2).first.update_attribute(:state, 'ACTIVE')
  end

  def remove_match(user2)
    inverse_friendship = inverse_friendships.where(user_id: user2).first

    if inverse_friendship
      inverse_friendships.where(user_id: user2).first.destroy
    else
      friendships.where(friend_id: user2).first.destroy
    end
  end

  # Friendship Methods

  # Filter Methods
  def self.gender(user)
    case user.interest
    when 'Male'
      where('gender = ?', 'male')
    when 'Female'
      where('gender = ?', 'female')
    else
      all
    end
  end

  def self.available_to_connect(current_user)
    @r = current_user.friendships.map(&:friend)
    @r2 = current_user.inverse_friendships.map(&:user)
    @rejected = current_user.inverse_friendships.where(state: 'reject').map(&:user)
    @active = current_user.inverse_friendships.where(state: 'ACTIVE').map(&:user)
    u = User.where.not(id: current_user.id) - @r - @rejected - @active
  end

  def self.not_me(user)
    where.not(id: user.id)
  end

  def matches(current_user)
    friendships.where(state: 'pending').map(&:friend) + current_user.friendships.where(state: 'ACTIVE').map(&:friend) + current_user.inverse_friendships.where(state: 'ACTIVE').map(&:user)
  end
  #
  def rejected(current_user)
    friendships.where(state: 'reject').map(&:friend) + current_user.friendships.where(state: 'reject').map(&:friend) + current_user.inverse_friendships.where(state: 'reject').map(&:user)
  end
  # Filter Methods

  private

  def self.process_uri(uri)
    avatar_url = URI.parse(uri)
    avatar_url.scheme = 'https'
    avatar_url.to_s
  end
end

app/models/user_interest.rb
class UserInterest < ApplicationRecord
  belongs_to :user
  belongs_to :interest
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to users_path if current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:comments).where(interest_id: current_user.interests.select(&:id))
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def destroy
    current_user.posts.find(params[:id]).destroy
    respond_to do |format|
      format.js
    end
  end

  private
  def post_params
    params.require(:post).permit(:text, :attachment, :interest_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login
  before_action :set_user, only: %i[edit profile update destroy get_email matches]

  def index
    @users = User.available_to_connect(current_user)
    if current_user.interest != 'Both'
      @users.select! { |o| o.gender == current_user.interest }
    end
    @users.uniq

    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    authorize! :update, @user
  end

  def update
    if @user.update(users_params)
      respond_to do |format|
        format.html { redirect_to users_path }
      end
    else
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
    if @user.destroy
      session[:user_id] = nil
      session[:omniauth] = nil
      redirect_to root_path
    else
      redirect_to edit_user_path(@user)
    end
  end

  def profile; end

  def matches
    authorize! :read, @user
    @matches = current_user.friendships.where(state: 'ACTIVE').map(&:friend) + current_user.inverse_friendships.where(state: 'ACTIVE').map(&:user)
    @users = User.available_to_connect(current_user)
    if current_user.interest != 'Both'
      @users.select! { |o| o.gender == current_user.interest }
    end
    @users.uniq
  end

  def get_email
    respond_to do |format|
      format.js
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def users_params
    params.require(:user).permit(:interest, :bio, :avatar, :location, :date_of_birth, :gender)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def name(user)
    if user.name
      case user
      when user
        user.name.partition(' ').first
      when @user
        user.name.partition(' ').first
      end
    end
  end

  def age(user)
    if user.date_of_birth
      case user
      when user
        age = Date.today.year - user.date_of_birth.year
        age
      when @user
        age = Date.today.year - @user.date_of_birth.year
        age
      end
    end
  end

  def location(user)
    if user.location
      case user
      when user
        user.location.partition(',').first
      when @user
        @user.location.partition(',').first
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tinstuk..</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=0.9">
</head>
<body>

<% if current_user %>
	<nav id="myNavmenu" class="navmenu navmenu-default navmenu-fixed-left offcanvas" role="navigation">
		<ul class="nav navmenu-nav">
			<li class="<%= if params[:action] == "index" then "active" end %> nav-btn">
				<%= link_to root_path do %><i class="fa fa-users"></i> Discover <% end %>
			</li>

			<li class="<%= if params[:action] == "matches" then "active" end %> nav-btn">
				<%= link_to matches_user_path(current_user) do %><i class="fa fa-heart"></i> Matches <% end %>
			</li>

			<li class="<%= if params[:action] == "edit" then "active" end %> nav-btn">
				<%= link_to edit_user_path(current_user) do %><i class="fa fa-cog"></i> Settings <% end %>
			</li>

			<li class="nav-btn"><%= link_to '/sign_out', method: :delete do %><i class="fa fa-cog"></i> Log out <% end %></li>

		</ul>
	</nav>

	<div class="navbar navbar-default navbar-fixed-top">

		  <button type="button" class="navbar-toggle button-nav" data-toggle="offcanvas" data-target="#myNavmenu" data-canvas="body">
		  	<i class="fa fa-cog"></i>
		  </button>

		  <%= link_to root_path, class: "navbar-brand" do %>
		  	<%= image_tag "logo.png", alt: "Tinstuk logo", class: "logo-brand" %>
		  <% end %>

		  <button type="button" class="navbar-toggle button-nav pull-right">
		  	<%= link_to matches_user_path(current_user) do %><i class="fa fa-heart"></i><% end %>
		  </button>

	</div>

<% else %>

	<a class="navbar-brand" href="#">
		<%= image_tag "logo_white.png", alt: "Tinstuk Logo", class: "logo-brand" %>
	</a>

<% end %>

<%= yield %>


<script type="text/javascript">

	$(".spinner").hide();

	$("#tinderslide").jTinder({

		    onDislike: function (item) {
          console.log(item[0].id);
          $("#user_" + item[0].remove());
          var data = { friend_id: item[0].id }
          $.ajax({
            type: 'POST',
            url: 'reject_friendship',
            data: data,
            success: function(response) {
            }
          });
		    },
		    onLike: function (item) {
          console.log(item[0].id);
          var myId = $("#tinderslide > ul li").last().attr("id");
          $("#user_" + myId)[0].click();
          $("#user_" + item[0].id).remove();
		    },

		    animationRevertSpeed: 200,
		    animationSpeed: 400,
		    threshold: 1,
		    likeSelector: '.like',
		    dislikeSelector: '.dislike'
	});

	$('.actions .like, .actions .dislike').click(function(e){
		e.preventDefault();
		$("#tinderslide").jTinder($(this).attr('class'));
	});

	$(".nav-btn").hover(function(){
		$(this).addClass("active2");
		}, function(){
		$(this).removeClass("active2");
	});


</script>
</body>
</html>